server:
  port: 8082

spring:
  datasource:
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USER}
    url: jdbc:mysql://localhost:3306/ccddttss
    password: ${DB_PASSWORD}
  jackson:
    time-zone: Asia/Seoul
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        use_sql_comments: 'true'
        show_sql: 'true'
        default_batch_fetch_size: 20
    hibernate:
      ddl-auto: update
