name: Java CI/CD with Gradle

on:
  # pull request가 develop에서 이루어질 때 ci/cd 실행
  pull_request:
    branches: [ "master" ]
  #release:
  #  types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2 # 만약 v1이라면 with의 distribution는 생략해도 된다.
        with:
          java-version: '17'
          distribution: 'zulu'

      # 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # gradle caching
      - name: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Build Gradle
      - name: Build with Gradle
        # test code는 빌드하지 않음
        run: ./gradlew assemble

      # DockerHub 계정 로그인
      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_PASSWORD}}

      # *.jar -> Docker Image Build
      # 디렉토리 이름은 마음대로 /air_dns_test
      - name: Docker Image Build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/air_dns_test .

      # DockerHub's Image push
      - name: DockerHub Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/air_dns_test

      # run application, ec2 client name : appleboy
      - name: Run Application
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            sudo docker kill air_dns_test
            sudo docker rm -f air_dns_test
            sudo docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/air_dns_test:latest
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/air_dns_test
            sudo docker run -d -p 8080:8080 ${{ secrets.DOCKER_ENV }} --name air_dns_test ${{ secrets.DOCKERHUB_USERNAME}}/air_dns_test:latest