name: Java CI/CD with Gradle

on:
  # pull request가 develop에서 이루어질 때 ci/cd 실행
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2 # 만약 v1이라면 with의 distribution는 생략해도 된다.
        with:
          java-version: '17'
          distribution: 'zulu'

      # 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # gradle caching
      - name: Gradle Caching
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Build Gradle
      - name: Build with Gradle
        # test code는 빌드하지 않음
        run: ./gradlew assemble

      # docker container builder driver를 사용하여 builder를 만들고 부팅
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 도커 허브에 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_TAG }}
